name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker Image
      run: |
        docker build -t ml-breast-cancer-classifier .
    - name: Run Docker Container
      run: |
        docker run ml-breast-cancer-classifier
